FROM apache/airflow:2.7.3-python3.10

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    dbt-core==1.10.4 \
    dbt-postgres==1.9.0
